name: 'build-sign'

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  build-tauri:
    timeout-minutes: 60
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target universal-apple-darwin --bundles dmg app'
          # Ubuntu build temporarily disabled
          # - platform: 'ubuntu-22.04'
          #   args: ''
          - platform: 'windows-latest'
            args: '--bundles nsis msi'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Using the full history like in the successful workflow

      # Install dependencies for Ubuntu (commented out since Ubuntu build is disabled)
      # - name: install dependencies (ubuntu only)
      #   if: matrix.platform == 'ubuntu-22.04'
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      # macOS certificate setup - keeping the exact same syntax that worked before
      - name: Import Apple Developer Certificate
        if: matrix.platform == 'macos-latest'
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          security find-identity -v -p codesigning build.keychain

      - name: Verify Certificate
        if: matrix.platform == 'macos-latest'
        run: |
          CERT_INFO=$(security find-identity -v -p codesigning build.keychain | grep "Developer ID Application")
          CERT_ID=$(echo "$CERT_INFO" | awk -F'"' '{print $2}')
          echo "CERT_ID=$CERT_ID" >> $GITHUB_ENV
          echo "Certificate imported. ID: $CERT_ID"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      # Ensure Windows bundlers are available (WiX for MSI, NSIS for EXE)
      - name: Install Windows bundler dependencies (WiX + NSIS)
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          choco install wixtoolset -y --no-progress
          choco install nsis -y --no-progress

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          # Using simpler cache config like in successful workflow

      - name: install frontend dependencies
        run: bun install
        
      - name: Extract app version on Unix systems
        if: matrix.platform == 'macos-latest' # || matrix.platform == 'ubuntu-22.04'
        shell: bash
        run: |
          APP_VERSION=$(grep -m1 'version =' src-tauri/Cargo.toml | cut -d '"' -f2)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Extract app version on Windows
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          $APP_VERSION = Select-String -Path src-tauri/Cargo.toml -Pattern 'version = "([^"]*)"' | ForEach-Object { $_.Matches.Groups[1].Value }
          echo "APP_VERSION=$APP_VERSION" >> $env:GITHUB_ENV

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_SIGNING_IDENTITY: ${{ matrix.platform == 'macos-latest' && env.CERT_ID || '' }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          MACOSX_DEPLOYMENT_TARGET: 11.0
          # Optimize Rust compilation
          CARGO_BUILD_JOBS: 4
          CARGO_INCREMENTAL: true
          # Speed up macOS build
          MACOS_TARGETS_OPTIMIZED: true
        with:
          args: ${{ matrix.args }}
      
      # Debug: list bundle outputs to verify build locations
      - name: List macOS bundle outputs (debug)
        if: matrix.platform == 'macos-latest'
        run: |
          echo "Listing src-tauri/target directory (depth-limited)"
          find src-tauri/target -maxdepth 3 -type d -name bundle -print -exec sh -c 'echo "== {} =="; ls -la {}' \;
          echo "Try listing known bundle locations"
          ls -la src-tauri/target/universal-apple-darwin/release/bundle || true
          ls -la src-tauri/target/release/bundle || true

      - name: List Windows bundle outputs (debug)
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          Write-Host "Listing src-tauri/target bundle directories"
          Get-ChildItem -Path src-tauri/target -Recurse -Depth 4 -Directory -Filter bundle | ForEach-Object { $_.FullName; Get-ChildItem -Path $_.FullName }
          
      # Upload artifacts by platform
      - name: Upload macOS artifacts
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: |
            src-tauri/target/**/bundle/macos/*.app/**
            src-tauri/target/**/bundle/dmg/*.dmg
          if-no-files-found: error
          retention-days: 7
          
      - name: Upload Windows artifacts
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: |
            src-tauri/target/**/bundle/msi/*.msi
            src-tauri/target/**/bundle/nsis/*.exe
          if-no-files-found: error
          retention-days: 7
          
      # Linux artifacts upload removed since build is disabled
      # - name: Upload Linux artifacts
      #   if: matrix.platform == 'ubuntu-22.04'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: linux-app
      #     path: |
      #       src-tauri/target/release/bundle/deb/*.deb
      #       src-tauri/target/release/bundle/appimage/*.AppImage
      #     retention-days: 1
